### ISSUE TITLE
Warhammer: Vermintide 2 Support

### ISSUE THREAD

**Issue by Nitzowsky** [antonpup/Aurora#1008]
Vermintide 2 have support for alienfx, can you add it?

tks in advance

**Comment by simon-wh** [comment]
You should be able to get it to work by applying the LightFX wrapper to the game directory.

**Comment by Nitzowsky** [comment]
Its working with wrapper, tks simon

**Comment by Thelgow** [comment]
I will give this a shot now. I just started playing the game and not sure if coincidence but Aurora has crashed on me 2-3 different times.

**Comment by simon-wh** [comment]
@Thelgow Could you post any of the crashes you've received? (If it is just logs you have just post them)

**Comment by Thelgow** [comment]
[2018-03-20 22.40.06.log](https://github.com/antonpup/Aurora/files/1835423/2018-03-20.22.40.06.log)

[2018-03-20 22.19.27.log](https://github.com/antonpup/Aurora/files/1835426/2018-03-20.22.19.27.log)

Heres one that just happened. Sadly this caused the game to crash as well once I clicked back on it, since the error from Aurora forced me out of full screen.
Mind you I had those few crashes prior to enabling the LightFX wrapper as mentioned. It looks like that made no difference.

**Comment by Thelgow** [comment]
@simon-wh Not sure if you saw my prior post. I have to keep Aurora disabled when gaming to not have this issue pop up.  Im thinking how to or if I should make a batch file to kill aurora, then run the game, then rerun aurora when done.

**Comment by simon-wh** [comment]
@Thelgow I currently have the flu and will try and look into these issues asap as your situation sounds pretty annoying.

**Comment by Thelgow** [comment]
@simon-wh I appreciate it but take your time. Flu's no joke. Oddly enough since the last crash I havent had any more. And I put in another 6+ hours I'd say.  I was having other video issues so I redid all my video drivers and also saw some AlienFX setting in game that I disabled. So not sure what else might have been affected. I did see the game changes my lights after I added the wrapper, but Ill admit in game Im not looking down so no idea what it really does.

**Comment by simon-wh** [comment]
@sausje Hm, that's strange. I'll try and have another look at the wrapper layer and see if I can sort that out.

@Thelgow I think those crashes, if you get them again should be sorted in the [lastest build](https://github.com/antonpup/Aurora/releases) if you come across them again.

**Comment by simon-wh** [comment]
Gonna close this as it appears the wrapper is working for it.
