### ISSUE TITLE
Sending raw data to SteelSeries instead of using GameSense

### ISSUE THREAD

**Issue by SnakePin** [antonpup/Aurora#1066]
### What are you experiencing an issue with?

- [ ] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [x] Aurora supported device, (SteelSeries Mouses)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [x] Enhancement suggestion
- [ ] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
Sending SteelSeries mouses RGB led data using something like this https://github.com/flozz/rivalcfg

### Actual behavior:
Aurora using GameSenseSDK to send rgb data which results in laggy rgb changes.

### What is the version of Aurora you are experiencing this issue with?

My version is... v0.6.1-dev4

**Comment by FHeilmann** [comment]
The other issue i see is that beyond something simple devices such as a 2 LED mouse this would get really messy (i.e. for a full size keyboard). And keeping two mechanisms around (gamesense and RAW) just to speed up the 2 LED mouse peripheral seems contra-productive.

**Comment by simon-wh** [comment]
@FHeilmann Yeah, that's a fair point. However, for Linux support I won't have much of a choice, I'll have to interact with the devices directly. I'm planning to set it up in such a way so that there is a plugin for all the Windows device integrations and one for all the Linux ones. With what I said above, if the implementation for Linux gets good enough it may make sense to use it instead of gamesense, but that all depends on if we get all devices supported.
