### ISSUE TITLE
Aurora Doesn't Work with Logitech G Hub

### ISSUE THREAD

**Issue by fin600** [antonpup/Aurora#1203]
### What are you experiencing an issue with?

- [ ] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [X] Other, Aurora has no means to patch the new G Hub that will be replacing the LGS Software

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [X] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
There should be a means of patching the Logitech G Hub or manually replacing the needed DLL files, but G Hub doesn't seem to use the same LogitechLed.dll as LGS if at all.

### Actual behavior:
Aurora can't control my keyboard anymore, but my because my mouse is still handled in LGS, it works fine.

### How often does this problem occur?
Constantly now that G Hub is installed.

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. Install G Hub
2. All supported G Hub devices will lose the ability to be affected by Aurora, even with G Hub turned off.

### What is the version of Aurora you are experiencing this issue with?
Beta 0.6.1 dev4

### Does the previous version of Aurora have this issue?
Yes.

### Please include any logs, screenshots, or files that are related to this issue:
https://www.logitechg.com/en-us/microsite/ghub

I hate this G Hub software but I can't uninstall it or LGS gets mad it's gone and makes me reinstall it to use my keyboard lighting. G Hub will fully replace LGS when it's out of beta, so it'd be good to work on support early.

**Comment by diogotr7** [comment]
As a quick fix, copying the legacy x64 dll from ghubs folder to the Aurora folder and renaming it LogitechLed.dll works, but breaks lgs compatibility from what I could tell.

**Comment by simon-wh** [comment]
You should be able to find a way to go back to LGS, I haven't done it personally but apparently, people have done it. If you need to use G Hub now follow what @diogotr7 has mentioned. Right now, as g hub isn't officially out we're going to stick with only supporting LGS right now, as there is no easy way to support both.

**Comment by Kisco** [comment]
Search "Add or remove programs" on windows, then find logitech G Hub and uninstall. There was no verification window for me but after loading back up LGS it didn't redirect back to G Hub and aurora worked again.

**Comment by Minotaur1975** [comment]
Which fole is the legacy x64 dll that needs to be copied? I tried legacy_sdk_x64.dll (and renaming to LogitechLed.dll) but it didn't seem to make a difference. The file sizes of the LGS and Ghub dll are also very different.

**Comment by Minotaur1975** [comment]
Would love to get this workaround working but am unsure of exactly which dll needs to be copied, and whether anything else needs to be done.

**Comment by simon-wh** [comment]
@Minotaur1975 Did you follow exactly what was described in the [release notes for v0.6.2](https://github.com/antonpup/Aurora/releases/tag/v0.6.2)?

**Comment by Minotaur1975** [comment]
I'd done that previously and it hadn't worked. Have tried it again and it's working this time.

**Comment by mbpakalin** [comment]
I tried what says on the release notes, but it didnt worked. Anybody knows how to fix this ?

**Comment by simon-wh** [comment]
@mbpakalin Try [this build](https://ci.appveyor.com/project/antonpup/aurora/build/0.6.2b-466) it should have ghub working out of the box

**Comment by Minotaur1975** [comment]
Build 466 working for me perfectly so far with GHub. Excellent work, thanks!

**Comment by Minotaur1975** [comment]
Follow-up to my previous comment. It's not working again. I have to manually go into Aurora settings_Device Manager|Restart All after a PC reboot in order to get it working. Build 466.

**Comment by simon-wh** [comment]
@Minotaur1975 Hmm, any errors in your log?

**Comment by Minotaur1975** [comment]
Actually yes. 
[ghub not running.log](https://github.com/antonpup/Aurora/files/2361397/ghub.not.running.log)
[ghub running .log](https://github.com/antonpup/Aurora/files/2361398/ghub.running.log)

I think what's happening is that Aurora is launching BEFORE G-Hub does on startup, causing the SDK error in the first log. Doing a restart all in the Device Manager section, or exiting and relaunching Aurora after GHub is loaded, results in it working fine, and it initializes fine.

**Comment by simon-wh** [comment]
@Minotaur1975 It should still work as the devices will automatically retry to initialize if they fail. You could try adding a delay to the task which opens Aurora on startup in Task Scheduler

**Comment by Minotaur1975** [comment]
@simon-wh Yeah I ended up doing something similar as a workaround

**Comment by incryptx** [comment]
I found a stupid workaround to get Aurora to work with G-Hub. I'll let the developer figure out why it works.

You will need the following files.
1) Aurora-v0.7.2+19.zip (contains the Elite profile)
2) Aurora-setup-v0.7.2.exe (Does not have the Elite Profile for some reason, Windows Installer)
3) G-Hub Installer

Now, 
1) Uninstall the G-Hub install completely.
2) Uninstall Aurora and delete the directory at C:\Program Flies\Aurora

Reboot your PC.

1) Install G-Hub from the installer, then close it without configuring anything.
2) Install Aurora-Setup-v0.7.2.exe, which will create the Aurora directory at C:\Program Files\Aurora without the "Elite Profile", but we will fix that in just a second.
3) Now, unzip Aurora-v0.7.2+19.zip somewhere, then go into the directory and "copy and paste" all the files directly on top of the directory at C:\Program Files\Aurora.

Now open G-Hub first, then Aurora and boom, your Elite Profile will work. You can go into G-Hub and enable integration, but Aurora should be already working.

As a side note, all of the game profiles I had in G-Hub were still there and all the settings I had for Aurora were still there, so I did not need to reconfigure either G-Hub or Aurora.

I don't know why this works, nor do I care. I uninstalled everything, reinstalled G-Hub after a reboot, used the Aurora-Setup-v0.7.2.exe to create the directory rather than unzip files and put it back there, then overwrote the Aurora directory with the zip file for the Elite Profile.

I have done this three times, it works every time.

**Comment by victorgorgonho** [comment]
Still having this issue rn with latest version... =/

**Comment by chuman72486** [comment]
Same, Aurora only applies to my Logitech keyboard if it loads _after_ G Hub.  If it happens to load first, I have to go into Task Manager and kill Aurora (just exiting the application doesn't seem to work) and then reload Aurora.  I suspect that Aurora is falling back to LGS when it doesn't see G Hub on start up and never attempts to reinitialize with G Hub later because it thinks it's already patched into LGS, even if LGS isn't installed.

**Comment by diogotr7** [comment]
@chuman72486 aurora has a delay option in the general settings. setting this to 15-30 seconds allows g hub to fully start before aurora does. should fix this issue.
