### ISSUE TITLE
Soft crash (for lack of a better term)

### ISSUE THREAD

**Issue by DaemonPhenex** [antonpup/Aurora#1241]
#### Aurora v0.6.2b
This typically happens when I restart my PC but aurora will launch as expected and after some time of using my computer (maybe less than 30min after boot) the keyboard will suddenly blank out on me... 
The aurora process within task manager will still be running but my keyboard lighting will blank until I shut down and restart "aurora.exe"

**Comment by DaemonPhoenix42** [comment]
I was not able to access the UI,
What I noticed was the -silent argument seems to result in my keyboard not change color at all. It was originally configured to run at the start with the UI settings but I have since bypassed that with the "task scheduler", removing the silent argument. I assume this isn't the intended effect of the argument, merely preventing the UI from appearing on boot? it just makes it non-functional in my case.
Give me the location of the log files and I'll see what I can do to replicate it if this is, in fact, an issue.

**Comment by simon-wh** [comment]
Hm, that's pretty strange, the silent argument is just designed to stop the UI from showing, you can disable that by changing the "start minimized" setting. The logs are stored in %appdata%/Aurora/Logs

**Comment by DaemonPhoenix42** [comment]
Yeah, that's what I thought...
So by passing the argument through cmd, It seems to function appropriately.
but this issue is mostly on initialization of the operating system.
do you suppose it has to do with the RGB driver? Say I have the SDK enabled for iCUE to pass info to Aurora. My only thought that could assist in the issue would be to add a delay factor to startup.
I will pass along the Logs momentarily when I get around to rebooting. Thanks for your time.
