### ISSUE TITLE
Game support: SCUM

### ISSUE THREAD

**Issue by LimticRage** [antonpup/Aurora#1243]
hello, could you look into SCUM (new survival game)? there is a lot of stuff and stats that could be used...

for Corsair K95 RGB Platinum, thanks!

**Comment by simon-wh** [comment]
I had a look around and it doesn't appear to have any native rgb integration so the wrappers can't work and doesn't appear to have mod support either so that's not an option. It doesn't appear to have much of an anti-cheat, so theoretically memory reading could work, but it looks like a game that will have something like battleye pretty soon. I also don't want to do memory reading for anymore actively updated games as it's difficult enough with just rocket league currently. Sorry
