### ISSUE TITLE
Profile copied to another game fails, crashes

### ISSUE THREAD

**Issue by Tuhljin** [antonpup/Aurora#1352]
### Expected behavior:
A profile can be copied from one game (or desktop settings) to another.

### Actual behavior:
Copying a profile from one game (or desktop) to another game (at least, a generic application added myself) results in lighting not working and, upon changing certain settings, causes a crash. There is also an error message about a corrupt profile when restarting Aurora.

### How often does this problem occur?
Every time I copied a profile to the game I added, the lighting didn't work. A crash occurred when clicking the "Preview profile during nighttime setting" button (and I would assume it would occur at other times, as well, though maybe with different error text). An error message appears upon restarting Aurora, indicating that a profile was corrupted and was reset to the default.

### Please describe the steps to reproduce this issue:
The issue can be reproduced with these steps:

1. Create a new profile for the Desktop Settings including lighting for you to test. (Mine had an interactive layer.)
2. Select the profile and press Ctrl+C.
3. Switch away from Desktop Settings by selecting a game you previously added (a "generic application"). (The problem *might* also occur for other games.)
4. Click the "Profiles" header for the game and press Ctrl+V to paste the profile.
5. Either click the "Overview" header and then check the box for "Preview profile during nighttime setting", or close Aurora completely and then start it again.

### What is the version of Aurora you are experiencing this issue with?
My version is beta v0.6.3.

### Does the previous version of Aurora have this issue?
Unknown. I haven't used another version.

### Please include any logs, screenshots, or files that are related to this issue:

Crash while using:
https://pastebin.com/VeFuehLu

Log afterward:
https://pastebin.com/sN8TbujS

**Comment by Gurjot95** [comment]
I noticed this before too. This is because of header in Desktop profiles is different than of wrapper game profiles.

The temporary solution is edit the header in json profile yourself. Open the desktop profile json file in Notepad you want to copy. (Profiles are stored in %AppData%Roaming/Aurora/Profiles). Look for the very first line there
`"$type": "Aurora.Profiles.Desktop.DesktopProfile, Aurora",`
replace it to
`  "$type": "Aurora.Profiles.Generic_Application.GenericApplicationProfile, Aurora",`
Save and move this file to new profile folder you wish to copy (Generic app profiles are generally stored in %AppData%Roaming/Aurora/AdditionalProfiles)

I know this is not convenient solution, I had the same doubts as you that this should have been basic feature to copy profiles. Hope @simon-wh can fix this issue soon.

**Comment by Tuhljin** [comment]
Thanks for the workaround.

I should add that it wasn't clear that you could copy profiles (or layers) at all using Ctrl+C and Ctrl+V. I only realized this could be done after I saw others comment about making copies (after which I simply guessed that Ctrl+C and Ctrl+V would be the method). I think it would be better if there was a right-click popup menu or a button or something that makes this more obvious (and the menu or button would indicate the keyboard shortcuts in a tooltip, so it's more intuitive).

**Comment by simon-wh** [comment]
Fixed with #1387
