### ISSUE TITLE
PLAYERUNKNOWN'S BATTLEGROUNDS

### ISSUE THREAD

**Issue by GugZi** [antonpup/Aurora#1385]
Support for pubg?

**Comment by Wibble199** [comment]
PUBG support is unlikely as there is no way of getting the game variables (such as health or ammo) directly from the game without memory reading. Since it's an online competitive game memory reading would almost certainly get the player banned so that's a no-no.

The only official way PUBG allows us to get data from the game is using their online API, however this has it's own issues:
1) Making a request over the internet is gonna be noticably laggier compared to being able to read directly from the game, making it feel less responsive than what we aim for. Imagine taking damage and then half a second later your keyboard updates.
2) The API is rate limited and by default each key is limited to 10 per minute. This means the keyboard would only be able to update **once every 6 seconds**. While it is possible to extend this limit, it's looked at on a case-by-case basis and we'd probably need each user to register their own API key and have it extended, which seems unlikely the PUBG team will allow.

So, unfortunately, there's little chance of getting PUBG support anytime soon :(

**Comment by Gurjot95** [comment]
Here: https://developer.playbattlegrounds.com/

**Comment by simon-wh** [comment]
From the comments above it appears that this is not an option at this time. Closing for now
