### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by Iruberiam** [antonpup/Aurora#1386]
Hi
The Logitech G910 has 9 G Keys, these are programable macro keys. They can be assigned as "Affected Keys" in the "Toggle Layer" but I can't find a way to assign them as "Trigger Keys". It would be amazing if this was possible.

Thanks in advance. Aurora is incredible.

**Comment by Wibble199** [comment]
Unfortunately I don't think this is possible since the way the trigger keys work is by listening out for Windows' keypress events. The programmable macro keys aren't a standard key and so Windows doesn't know when you press them. What happens when you do press them is the keyboard or the Logitech software converts that into some other behaviour as set in the software such as keyboard combination (e.g. <kbd>Ctrl</kbd>+<kbd>N</kbd>) or a recorded sequence of keys or whatever.
