### ISSUE TITLE
Fading effect not fluid & suggestions

### ISSUE THREAD

**Issue by Shadow091995** [antonpup/Aurora#146]
Hey,
I noticed the fading effect does not fade in and out fluidly. It always does a little stop in between, no matter, if the team fade-out in CG:GO or the Color breathing effect. (Video: https://drive.google.com/file/d/0B6QWNlEVPXoJaS1xS2l6ZFR6WWc/view?usp=sharing )

I also have a suggestion: Is it possible to use a sliding effect just like in Artemis? Like Rainbow Shift, just with custom colors? (Artemis Screenshot: http://prntscr.com/cj34oi )

**Comment by antonpup** [comment]
That happens because you have "Enable color enhancing for Logitech Devices" checked under the Devices & Wrappers tab. It was a feature that I added for the wrappers, because Logitech's LEDs don't seem to be as bright in terms of sent colors, so that was giving them a little boost. I don't think that feature will stay for the next major version though.

As for the sliding effect, yes you can create that effect in Aurora. I do now understand that it is slightly difficult to get to, I will make it straightforward for next major release. Here's how you can set it up for the current version. Create a new color zone and select "Gradient Shift (Cutsom Angle)" as the effect. Select whatever keys or freeform that you want for the zone. Then press the "..." button next to the zone effect selection. It will bring you to a new window, you can set the effect speed, angle, etc. When you click on the "Effect Gradient" it will allow you to set the gradient. (For my example I will set it to transparent to green to transparent) It should look something like this: 
![](http://puu.sh/rewrp/e293d4f514.jpg)

Here's how the rest of my windows look and the effect.
![](http://puu.sh/rewy6/40f834ddfc.png)
![](https://dl.dropboxusercontent.com/u/30675690/Aurora/gradient_shift_demo.gif)

**Comment by Shadow091995** [comment]
Okay! It works and I like it! :D

Oh and what I totally forgot to ask, are you adding some kind of audio visualizer in the future? :D

**Comment by antonpup** [comment]
Yes. #34 should be part of next major version.
