### ISSUE TITLE
Elite Dangerous Support

### ISSUE THREAD

**Issue by KaHonu** [antonpup/Aurora#1468]
There is already a Logitech 'Arx' app out there that provides some RGB effects from Elite Dangerous, but it's designed for the Logitech G19 keyboard so it does not support 'per-key' lighting. It only changes the entire color of the device. It's called the Elite G19s Companion App and I have confirmed it does work with the Logitech Wrapper. The primary purpose of the app is not RGB support so I'd rather run something that's made for RGB effects since I don't use any other features of the app.

More robust effects for Elite Dangerous could be added through Aurora. The game keeps a 'Player Journal' in C:\Users\%userprofile%\Saved Games\Frontier Developments\Elite Dangerous that could be parsed for events while the game is running. I think this is what is done with the companion app.

**Comment by diogotr7** [comment]
I searched around for a bit and found this, which looks to be a better alternative to what you suggested. https://github.com/EDCD/EDDI

**Comment by Wibble199** [comment]
I have tried implementing a thing with the player journal however I found that it wasn't reliably updated except when jumps were made. Additionally, when dealing with things such as health and shields, it was only adding an entry every 20% (I think, it was a while ago when I tried this).

Basically though, it meant that we wouldn't be able to add GSI variables for health/shields because they might not actually update until you next jump out of the system.

That EDDI thing looks promising though and I shall look into it again soon.

**Comment by KaHonu** [comment]
Adding this to the list of resources. Looks promising:

https://forums.frontier.co.uk/threads/rgb-keyboard-support-for-elite.521011/

**Comment by diogotr7** [comment]
That is a fork of aurora available here: https://github.com/DrParanoia/Aurora

**Comment by KaHonu** [comment]
Can this be included in the next release of Aurora? That fork is outdated.

**Comment by DrParanoia** [comment]
@simon-wh @diogotr7 This issue can be closed now :)
