### ISSUE TITLE
Aurora support for Anthem

### ISSUE THREAD

**Issue by darxy4n** [antonpup/Aurora#1486]
Please enable lighting effects for Razer and other peripherals for Anthem!

Have not been able to get Aurora working despite some people saying that they are able to patch Anthem.

**Comment by blixem** [comment]
Been working with thatsickman on this issue over discord.  

So far, my best guess is that Anthem is setting a default lighting state with bitmap and then updating with key/scan codes.  Since Aurora doesn't have the Logitech keyboard Bitmap keys method implemented yet; the flickering might be the key not having a proper "default lighting state" set with bitmap.

**Comment by simon-wh** [comment]
Duplicate of #1459
