### ISSUE TITLE
[CSGO] Bomb effect request

### ISSUE THREAD

**Issue by predator1234** [antonpup/Aurora#157]

**Comment by predator1234** [comment]
Hello 
Can you make a profile just exactly like https://youtu.be/qkxvznjeX2U 
it will be so helpful for me in CS:GO because Im deaf in real life so can see bomb counting down. Really hope you make it for me and my deaf friends pls

Thank you

**Comment by predator1234** [comment]
Sorry Im new to this website, a bit confusing for me lol. Forgot to add keyboard name, mine is k70 LUX if that helps

**Comment by antonpup** [comment]
I can probably add that, do you want the full implementation? The F-key timer, and defuse kit ranges? There's a small issue with the ranges, though, they will be slightly inaccurate because the game reports inaccurate time on purpose.

**Comment by predator1234** [comment]
Yes please. So i will still know when to run away from bomb explosive.
Little inaccurate is still good for me though! :)

**Comment by predator1234** [comment]
bump

**Comment by antonpup** [comment]
You don't need to bump. It will be in the next major version.

**Comment by predator1234** [comment]
Oh sorry. Awesome thanks heaps! :)

**Comment by antonpup** [comment]
I wanted to include this in 0.6.0 but I have forgotten. I'll look into it later. My apologies.

**Comment by Sparqey** [comment]
I would like to touch up on this, the bomb% on the top will infact prevent you from playing on a VAC secured server, there is an app on android and ios, that allows you to see in detail stats on your LIVE csgo match you are playing right now, stuff like your map your kills/deaths health bullets armor etc, users got a VAC triggered and where kick'd from the match because of the live 40 seconds countdown that the app had, they removed the countdown and it was fixed

**Comment by gunnerwolf** [comment]
Yeah there's no indicator of how close the bomb is to exploding beyond the beeping and for good reason, while it is possible to make such timers, Valve and VAC consider it a cheat, and it will likely get you banned.
