### ISSUE TITLE
Issue when having two rgb mousemats connected at the same time.

### ISSUE THREAD

**Issue by noisyboi** [antonpup/Aurora#168]
So, in the new version of Aurora the MM800 got added, and works perfectly fine, however the razer firefly ceases  to work when they both are connected now, is it a limitation in Aurora that does this or could it be made to use both at the same time?

Edit: it does not do anything to the Firefly at all in the new version of aurora, If I rollback to the previous version it works fine hmm....

**Comment by antonpup** [comment]
I do not have a Razer Firefly, nor do I have access to any Razer product to debug/test with. It's part of the code, it should function. But the device integrations do not hinder one another, they are independent. Aurora basically sends to each device integration a list of colors for each key. What they do with that information does not rely on any other device.

The reason why I was able to get MM800 to work, was because it's emulated in CUE 2 as a demo.

**Comment by noisyboi** [comment]
ah, well the firefly do not work even on it's own now, is there anything I can do to help you figure it out?

**Comment by noisyboi** [comment]
Issue is solved, apparently windows loads Synapse after Aurora, I manually changed the load order on windows stat up and now Both mouse mats are confirmed to work!

**Comment by antonpup** [comment]
Alternatively, you can press "retry for connected devices" in Aurora settings, and it will retry to load all SDKs.

But I am glad that I didn't fuck it up and it works. :)
