### ISSUE TITLE
Audio Visualizer Layer

### ISSUE THREAD

**Issue by roshanbanik** [antonpup/Aurora#1693]
First of all thanks for creating such an amazing software. 
Is there any option for adding frequency higher than 16000hz in the audio visualizer layer as my alienware 15 R3 has 24bit 48000hz frquency. Please add this support & will also be highly grateful if particularly AW 15R3 support is being added.

**Comment by diogotr7** [comment]
Frequency (the 16000hz you mentioned) and sample rates (48khz) are measured by the same unit but are not the same thing. 

90% of all songs you have which are probably either mp3 or spotify/youtube don't even reach those high frequencies due to compression. And even if they did, these frequencies aren't captured all that well to the human hear.

as for the alienware support, that's for another issue

**Comment by roshanbanik** [comment]
Shall i need to change any of the settings in sound properties?
because after enabling the layer with the audio visualizer mode does show up any lighting with any of the apps like spotify, youtube, itunes or even groove music... can you suggest me the steps how to enable that layer for AW 15R3
