### ISSUE TITLE
Ü Key on german layout not lighting up anymore + Crashes

### ISSUE THREAD

**Issue by Shadow091995** [antonpup/Aurora#170]
Hey, 

Issue 1: 
since today the ü-key (right of the p-key) on my G810 does not light up anymore (really with no preset) in your software. Artemis and the Logitech G software can still light up every key, so it's not broken.
I didn't change any settings, and the layout is set to german (but i tested every other layout too), but it won't light up anymore.

Issue 2:
When I start Aurora, I get 2 Error messages from Windows. 
1. Aurora-SkypeIntegration stopped working. (almost every time Aurora starts)
2. Aurora-Updater stopped working. (this is mostly when I start up my PC, but also sometimes when I restart Aurora)

Hope you can help :)

**Comment by antonpup** [comment]
Skype Integration and updater only crash on Windows start up?

The key issue is my mistake. I will push a fix this weekend.

**Comment by Shadow091995** [comment]
Okay thank you :)

Skype Integration crashes in 99% when starting
Updater mostly crashes on windows startup, but I had it crashing also when just restarting Aurora, but very rarely.

**Comment by antonpup** [comment]
Ok, that was never reported. I will look into the skype issue.

**Comment by Shadow091995** [comment]
Thank you :) And btw it also crashes immediately when I click on "Start Skype Integration Listener" just for your notes.

**Comment by antonpup** [comment]
Using the latest version, I presume? Can you provide me with your latest Aurora log? Should be in the "logs" directory.

**Comment by Shadow091995** [comment]
version is beta v0.5.1c


[2016_07_10.txt](https://github.com/antonpup/Aurora/files/517008/2016_07_10.txt)
(just renamed it from .log to .txt to upload it here :) )

**Comment by antonpup** [comment]
I know why SkypeIntegration was crashing, it's fixed in 0.5.1d.
I also have fixed my mistake with foreign Logitech layouts.


However, the issue with Updater crashing on Windows startup is related to Aurora trying to launch an application with admin permissions while it itself ran with admin permissions (from system). It's a way to prevent unauthorized applications from just running random apps as admin. It's addressed in the next major version. But I would like to keep 0.5.1d changes as minimal as possible.
