### ISSUE TITLE
Problem with ETS2.

### ISSUE THREAD

**Issue by vaio2005** [antonpup/Aurora#1733]
[2019-10-01 10.57.07.log](https://github.com/antonpup/Aurora/files/3675648/2019-10-01.10.57.07.log)

### Expected Behaviour
The keyboard should get the lightning effects from the software
### Actual Behaviour
The keyboard continues the normal lighting effect

### Reproduction steps
(for me) Open the Aurora program, Insert DLL (thru the app), and open the game. 

### Frequency
Always

### Aurora Version:
Beta v0.6.4b

### Previously an Issue?
Don't know

**Comment by Wibble199** [comment]
The error in the log you provided states that Aurora cannot access the file because it is in use by another program. This would imply that the required DLL for Euro Truck has been installed correctly and is in use by the program (do not attempt to re-patch it while the game is running).

If the lighting "continues the normal lighting effect" then it sounds like either the ETS2 profile is disabled or there is an issue detecting which applicaton is currently running. Aurora should show the ETS2 profile regardless or not if the DLL has been installed. If the keyboad does not go blank with the E key lit up, then this will be the problem. Ensure the profile for ETS2 is enabled by right-clicking the game's icon in the left hand side bar and ensuring there is a tick next to "Enabled". If this does not resolve the issue, try changing the foreground application detection method in the Aurora settings.
