### ISSUE TITLE
Saitek X52 Flight Control System

### ISSUE THREAD

**Issue by furgoose** [antonpup/Aurora#1759]
Please add support for the following device:

**Device Name:** Saitek x52pro

**Device Website:** https://github.com/nirenjan/x52pro-linux

**Comment by josh26turner** [comment]
I'd love to see support for this

**Comment by wolfcomp** [comment]
That is a **Linux** based thing where Aurora is only **Windows** based

**Comment by furgoose** [comment]
I was assured by @simon-wh that aurora is supporting linux also. However **this device** also supports **windows**, as seen here with a **2 second** google search. **https://www.saitek.com/uk/down/drivers.php**

@simon-wh do you have any input?

**Comment by josh26turner** [comment]
Yeah but Aurora is being released on Linux 
@simon-wh this is coming soon is it not?

**Comment by wolfcomp** [comment]
As it currently sits Aurora is **Windows** only due to WPF and all hardware Aurora suports all has **SDK**s open to the public.
What you linked is a **Driver** and not an **SDK** and after looking around for an **SDK** for the x52 i found one tho it would take a bit of trail and error to get it working as i dont possess a x52 _tho i have friends that has it_ and it is only on **Windows**

**Comment by Wibble199** [comment]
While we would like to release on other operating systems beside Windows, it is very much a distant plan - there is a long way to go before we would be able to support Linux. This is due to many things, including:
- The interface. We use a technology called WPF which is Windows only and the WPF development team have no plans to make it cross-platform.
- Many of the SDKs we use (which is what Aurora needs to talk to the devices) are Windows exclusives, so either the device vendors would have to issue a cross-platform SDK (which is very unlikely) or the dev team would need to reverse engineer the data that is sent from the computer to the device (which is a huge task for even one device, nevermind numerous devices across numerous makes).
- Code that does things such as detecting keyboard input (for the interactive layers) or figuring out which program is currently in the foreground is platform-specific. It was also not made in a way that is easy to "swap out" for other code. We'd need to rewrite big portions of the code to be able to be conditionally built for different platforms.

We do intend to address these concerns (and are already addressing some); however I would not hold your breath for a Linux release anytime soon.

---

That being said it **may** be possible to replicate the code in the repository you linked and make it work with Aurora.

I must ask though, since Aurora is a RGB lighting program, what do you hope to achieve by making it work on this device? Correct me if I'm wrong, but as far as I can tell it's not got any RGB capability?
