### ISSUE TITLE
Discord overlay profile is black

### ISSUE THREAD

**Issue by QuentinMcCarthy** [antonpup/Aurora#1769]
### Expected Behaviour
The Discord profile should continue to use the Desktop profile regardless of focus, however overlaying the Discord profile wrapper upon certain events (mentions, DM's, etc)

### Actual Behaviour
The Discord profile sets the keyboard completely black if Discord is in focus

### Reproduction steps
Create the Discord profile using discord.exe, create a Wrapper layer in Overlay Layers. Ensure Logitech patch is working. Disable the layer but keep Overlays Enabled checked. Put the Discord app in focus.

![image](https://user-images.githubusercontent.com/36647653/67458167-fa355200-f691-11e9-99e4-6a3ad462838b.png)
![image](https://user-images.githubusercontent.com/36647653/67458153-f0abea00-f691-11e9-856c-e6db4e1a3cd3.png)
![image](https://user-images.githubusercontent.com/36647653/67458117-dc67ed00-f691-11e9-9c78-d388d0ebc64b.png)

### Frequency
This issue occurs every time.

### Aurora Version:
beta v0.7.0

### Previously an Issue?
Don't know

**Comment by Wibble199** [comment]
The main reason this doesn't work is because (if I remember correctly) the wrappers do not send transparency to Aurora. The wrappers do not differentiate between keys they are set and those that aren't, so there's no way of Aurora being able to know which is which. We also believe the Discord applet is designed to work with Logitech's software in such a way that the overlay is calculated by that software and then the whole keyboard result is then sent to Aurora (which again, means that there are black keys where you would expect transparency).

For these reasons we don't really advise the use of the Logitech applets at the same time as you are attempting stuff with Aurora.

If you use BetterDiscord, there is plugin support for that. Otherwise, there's not a lot the Aurora team can do as normal Discord does not have an API for fetching this type of data.
