### ISSUE TITLE
Add support for more LightFX games

### ISSUE THREAD

**Issue by antonpup** [antonpup/Aurora#18]
List is taken from [http://alienfx.cyanlabs.net/](http://alienfx.cyanlabs.net/), a few notable games:
- [x] Anomaly 2 (Works with changes, next version of Aurora)
- [ ] APB Reloaded
- [x] Battlefield 3 (Works beautifully, no modifications to Wrapper Required, will work with current version of Aurora)
- [ ] BeatBuddy: Tale of the Guardians
- [x] Blacklight: Retribution (Works with changes, next version of Aurora)
- [ ] Dying Light
- [x] Guild Wars 2
- [ ] Loadout
- [x] Magic The Gathering 2012 (Works with changes, next version of Aurora)
- [ ] Magic 2014
- [ ] Mass Effect 3
- [x] Metro: Last Light
- [x] Middle-earth: Shadow of Mordor (Works with changes, next version of Aurora)
- [ ] Orcs Must Die! 2
- [x] Quantum Conondrum
- [x] Robot Roller-Derby Disco Dodgeball
- [x] Serious Sam 3: BFE (Works with changes, next version of Aurora)
- [x] Shadow Warrior
- [ ] This War of Mine
- [x] XCOM: Enemy Unknown (Works with changes, next version of Aurora)

**Comment by RoboKun** [comment]
Another game that supports LightFX is BeatBuddy: Tale of the Guardians, which appears to be missing from this list

**Comment by antonpup** [comment]
@RoboKun I don't own that game, but I will add it to the list.

Downloading tons of games, will be looking to add support for: 

- APB Reloaded
- Battlefield 3
- Blacklight: Retribution
- Guild Wars 2
- Loadout
- Magic The Gathering 2012
- Serious Sam 3: BFE
- XCOM: Enemy Unknown

**Comment by antonpup** [comment]
With recent changes to LightFX wrapper, I feel like all LightFX games are now supported. Only way to find out is to test. For now, I will consider all games from the http://alienfx.cyanlabs.net/ list to be supported, but not tested.

**Comment by stuntguy3000** [comment]
![image](https://cloud.githubusercontent.com/assets/1522389/16644809/c7752f54-445e-11e6-9ed3-e09d942f5183.png)

//litertally dying at the thought of MS Outlook reactive LEDs

**Comment by antonpup** [comment]
More games to try

- Broforce (Works with upcoming version)
- Nexuiz
- Quantum Conondrum
- Shadow Warrior

**Comment by stbatuhan** [comment]
Any plans on Mass Effect 3 and other games? Or it has build in support but not checked here bec of not tested?

**Comment by brainbug89** [comment]
> Or it has build in support but not checked here bec of not tested?

It should work with the LightFX wrapper of Aurora, but no one has tested it yet. So if you own Mass Effect 3 feel free to test it with the LightFX wrapper and report back. :wink:

**Comment by stbatuhan** [comment]
Well i will give a shot. As i remember i don't have it but i will with EA Access on September (With addition of BF1) and will write here.

**Comment by diogotr7** [comment]
For some reason I can't get Dying Light to work. I added the exe to a profile, added the lightfx wrapper(64-bit) and it still doesn't work. Also tried re-checking game data with steam. It's weird because I know it did work before( the colors flashed but at least something happened). Now I can't get anything to appear. I'm using Aurora 0.6.0-dev2

**Comment by simon-wh** [comment]
@diogotr7 Could you try it without creating a profile in Aurora for it? Also, you could try updating to the latest development release to see if that makes a difference if it doesn't work after that.

**Comment by diogotr7** [comment]
I just tried updating and it turns out I was already using the most up to date version, but in the "About" section it still says 0.6.0-dev2. Anyway, even with the profile deleted it doesn't change from the desktop profile. I have the option "Allow wrappers to take priority over desktop" active, if that makes any difference.

**Comment by diogotr7** [comment]
@simon-wh Today I was testing Dying Light and I can confirm it works pretty consistently as long as I don't have a profile created for it. If I do, I get this [log](https://pastebin.com/YqZrvJHf) and it doesn't display anything on the keyboard except the layers I configured manually.

**Comment by brainbug89** [comment]
The error gets thrown here: https://github.com/antonpup/Aurora/blob/dev/Project-Aurora/Project-Aurora/Profiles/LightingStateManager.cs#L636

The problem is, that the SetGameState method isn't implemented here: https://github.com/antonpup/Aurora/blob/dev/Project-Aurora/Project-Aurora/Profiles/Generic_Application/Event_GenericApplication.cs#L55

**Comment by diogotr7** [comment]
If I don't create a profile it works perfectly but keeps throwing out this line repeatedly on the log 

[INFO] Unknown Wrapper Command: LFX_GetNumLights

everytime the lightning updates.

**Comment by simon-wh** [comment]
With my plan to make the wrapper lighting into a layer for v0.7.0 it should allow you to create a custom profile for an application that uses a wrapper.
