### ISSUE TITLE
Game Request

### ISSUE THREAD

**Issue by SoCoolMuchGitHub** [antonpup/Aurora#1881]
Have you guys considered adding Apex to the list of supported games? I feel like a lot of cool effects could come out of that, like separate profiles for the legends and effects if you use their tacs and ultimates.

**Comment by Wibble199** [comment]
Having such an interactive profile is sadly not something we can achieve with Apex. We'd need to be able to get this information from the game somehow. Ideally the game would expose the data itself (such as how CS:GO does) or we'd create a mod (such as we do for Terraria). As a fallback we can also try using memory reading, but this is difficult to maintain with game updates etc.

Since Apex does not expose these values nor does it have modding we can't do that, and we won't implement memory reading for online games as it will almost certainly trigger anti-cheat mechanisms.

I believe that Apex does have Razer Lighting integration so you _should_ be able to use it with the Razer Chroma layer, but you will only be able to have the lighting as set by the developers and won't be able to customise it.

**Comment by diogotr7** [comment]
This is correct, the game should work with the razer chroma layer as overwatch does.
