### ISSUE TITLE
Req: Ambilight support.

### ISSUE THREAD

**Issue by Sokonomi** [antonpup/Aurora#193]
I would love it if I could assign 'ambilight' to a zone.

Razer already has such a feature, where it colors the peripherals to match the monitor infront of it. If you look up to a blue sky, your devices would turn blue. Look at some grass and they turn green, etz.

It adds a ton of immersion. Its great for games as well as movies.

https://www.youtube.com/watch?v=jrTWqH6886w

**Comment by antonpup** [comment]
Ambilight is part of dev.

**Comment by Sokonomi** [comment]
How do I get my hands on a dev build? I'm not too savvy with all this github stuff. :')

**Comment by antonpup** [comment]
If you don't want to compile the source code, then you can't.
If you can compile the source code, then [https://github.com/antonpup/Aurora/tree/dev](https://github.com/antonpup/Aurora/tree/dev).

**Comment by rkkoszewski** [comment]
Hi @antonpup.
I just noticed a bug in the Ambilight implementation.

By default Ambilight is taking about 0,2% of CPU for me. With Ambilight enabled it goes up to arround 5 - 6%.

The bug I've noticed is that once you enable the Ambilight Layer it takes up the extra CPU, when you hide it or even remove it completely, it keeps using CPU cycles and stays like that until you close Aurora completely and restart the app.

**Comment by antonpup** [comment]
Yeah, I know what the problem is. Ambilight layer isn't exactly optimized. Essentially once an ambilight layer is initialized, it starts a static loop that constantly fetches an image that can be used by all ambilight layers, so if you have 30 ambilight layers, you only fetch image once instead of 30 times.

The problem is that I never implemented the way to detect when there are no instances of ambilight layer that need the images. Thus the loop never stops once started.
