### ISSUE TITLE
Aurora fatally crashes on startup

### ISSUE THREAD

**Issue by andrixbooom** [antonpup/Aurora#1980]
### Expected Behaviour
Access the program when I launch the application

### Actual Behaviour
As soon as the application starts, it fatally crashes. This happens both if I run it manually, and when it automatically starts at the boot of windows. This happens after many system restarts. I already tried uninstalling Aurora and setting it back up with the provided exe on github. I did so more times, hoping it would delete eventual register files that were corrupted, with no success.

### Reproduction steps
Open the application. 

### Frequency
Every time

### Aurora Version:
0.7.2 

### Previously an Issue?
No, it previously didn't have this issue, but the application doesn't work even if I install 0.7.1 or even 0.6.2

Screen:
https://i.imgur.com/jyGtUBk.png

Log:
[2020-04-25 11.23.08.log](https://github.com/antonpup/Aurora/files/4532700/2020-04-25.11.23.08.log)

**Comment by Gogosoft** [comment]
Windows 10 Pro (x64) cold start:

Me chrash-log:
[2020-04-25 17.52.17.log](https://github.com/antonpup/Aurora/files/4533479/2020-04-25.17.52.17.log)

And the log from starting Arora again:
[2020-04-25 18.10.18.log](https://github.com/antonpup/Aurora/files/4533480/2020-04-25.18.10.18.log)

**Comment by Flexxkii** [comment]
Does removing Aurora restore your system?

**Comment by adiac** [comment]
I encountered the same problem with the last update I installed today.

Log before the update
[2020-05-28 09.48.12.log](https://github.com/antonpup/Aurora/files/4694254/2020-05-28.09.48.12.log)

Log with crash after the update
[2020-05-28 10.17.14.log](https://github.com/antonpup/Aurora/files/4694257/2020-05-28.10.17.14.log)

Log with second attempt to start up the program
[2020-05-28 10.19.11.log](https://github.com/antonpup/Aurora/files/4694261/2020-05-28.10.19.11.log)

I haven't tried anything else to fix the issue.

**Comment by diogotr7** [comment]
It looks to me like @andrixbooom 's problem is a faulty installation. Try reinstalling aurora, but make sure you delete the Program Files\Aurora folder completely.

@Gogosoft it looks from the log that somehow your settings got corrupted? If you move / rename the Aurora Appdata folder (%appdata%\Aurora) does it start properly?

@adiac , your issue is caused by aurora trying to load the outdated example plugin. I will add error handling to the plugin loading, but meanwhile you can delete the example plugin (should be in the exe directory -> plugins)

**Comment by andrixbooom** [comment]
@diogotr7 Yep, I alredy tried reinstalling Aurora after cleaning the program files folder. Even snooped in AppData.

**Comment by diogotr7** [comment]
I wonder if maybe some dependencies are missing. Did you use the installer or the zip when you got aurora?

**Comment by adiac** [comment]
> @adiac , your issue is caused by aurora trying to load the outdated example plugin. I will add error handling to the plugin loading, but meanwhile you can delete the example plugin (should be in the exe directory -> plugins)

Yes, that fixed the issue. Thanks.

**Comment by andrixbooom** [comment]
> 
> 
> I wonder if maybe some dependencies are missing. Did you use the installer or the zip when you got aurora?

This made me doubt, I may have been using the zip version.
I tried uninstalling it, making sure to delete every user data, resetting my system then installing it back with the 0.8.0rc1 exe and now it's working.
Thanks for your help, fixing Aurora was getting kind of frustrating honestly.

**Comment by diogotr7** [comment]
Since the setup installs everything needed for aurora to work, you should be able to use zips from now on if you prefer.

**Comment by Qzattitude** [comment]
I believe its due to the windows defender.
It deleted some dll files. please check yours.

I restored them (Technically 3 to 4 files are marked as threats) and the app is running again.

<img width="487" height="460" alt="Image" src="https://github.com/user-attachments/assets/6303ae55-f701-469f-a05f-615506a809d0" />
