### ISSUE TITLE
Support for Redragon K550

### ISSUE THREAD

**Issue by pooky1225** [antonpup/Aurora#2032]
I noticed there are device requests for other redragon products. It also seems there might be support for the K550 on OpenRGB, but won't bother to change out drivers to see it possibly fail. There does not seem to be a public SDK, but I did email them asking if there is one. 
EDIT: I forgot to add, there is a software for this keyboard [labeled driver], but it does what the keyboard does on-device.

**Device Name:** YAMA K550
**Device Website:** http://redragonusa.com/products/keyboard/K550/33

**Comment by diogotr7** [comment]
The keyboard only supports setting its lighting by writing to the flash. This means it is impossible to get fluid effects, the keyboard will be unresponsive while aurora is running since it's too busy writing the effects to flash to send keystrokes (so that means you'll have a fancy paperweight) and the constant writes will make the flash break  much sooner than normal.
