### ISSUE TITLE
game dont uses dll, but xml file

### ISSUE THREAD

**Issue by cyrok** [antonpup/Aurora#2066]
got trover saves the universe yesterday on the steamsale, and found out about aurora. i installed every thing but the thing is, the game dont loads the razer dlls (it has a massive library of .chroma files and official support for razer led stuff).
any way to get the xml working/recognized?
i am using a k95 platinum

**Comment by gitmacer** [comment]
You should try the new method instead of the wrapper method. Download v0.8.0 and remove the dlls inside the game folder. Then install the razer broadcaster over the settings and create a profile for it or add a razer layer to the desktop profile.

**Comment by cyrok** [comment]
> You should try the new method instead of the wrapper method. Download v0.8.0 and remove the dlls inside the game folder. Then install the razer broadcaster over the settings and create a profile for it or add a razer layer to the desktop profile.

thank you ^^ searched for this broadcaster, but found nothing but the streaming stuff from razer and in settings just again the wrapper patch. anyway, works hust fine, thanks :)

another question, so i dont boother the dev, anyway to get normal rgb tools integrated? i use an equalizer for my keyboard. it looks like its not working with aurora...

**Comment by gitmacer** [comment]
I was talking about this chroma setup. This method works with every game. The wrapper method does not work for every game because some games block dll loading. ![unknown](https://user-images.githubusercontent.com/37345589/83846031-3c377380-a70a-11ea-9da8-27aa808766c3.png)
Can you precise what you mean with normal rgb tools?
I have to few information to know why the audio layer does not work. Also I would suggest to contact us over Discord for fast help.
BTW: I would consider myself as dev just take a look at the changelog 😄

**Comment by cyrok** [comment]
i didnt mean the audiolayer. its an external tool that creates the visualiser. i think its not posible the way i have it in my mind, but i think i could recreate it in aurora. i created anew ticket with improvement marker. the main course of this thread got resolved. tryed and worked. was just wondering what you mean with razer broadcaster. its the sdk i think...
