### ISSUE TITLE
Heavy compatibility Issues with asuse`s shitty armoury crate on my Rog Strix 

### ISSUE THREAD

**Issue by NicTanghe** [antonpup/Aurora#2201]
If you have log files or screenshots that may help, please also attach them to the issue. The logs can be found in %APPDATA%\Aurora\Logs
-->
### Expected Behaviour
It should work the same as it does when i close the lid of my laptop	

### Actual Behaviour

If my laptop lid is opened and it`s keyboard activates.
There are a lot of weirdo bugs. if i type it copies what should be displayed on the laptop keyboard on my external keyboard. ALso the following pop-up appears.
![rhlhCvGhF6](https://user-images.githubusercontent.com/13624265/95743876-be284200-0c92-11eb-88ae-0b559dc69355.jpg)

This is however not the case for all the things because my cpu usage meter and my ram usage meter stull display correctly.

I also get the following pupup even if i run as admin. I would appreciate it if someone from the core dev team would contact ASUS and ask them if you can find a way to work together to resolve multiple issues with their laptops. (Like grabbing the audio ect.)

### Reproduction steps
Try to use aurora on a rog strix with the lid open.

### Frequency
every time the lid is open

### Aurora Version:
latest

### Previously an Issue?
Don't know

**Comment by diogotr7** [comment]
In Aurora all keyboards are handled the same, so all the effects will apply on all the keyboards it finds. Also, windows does not distinguish which keyboard sent which input, so we can't do interactive effects per beyboard anyway.

The popup usually happens because there's another service running on the port aurora uses for the gamestate server (9088). You have to find what is using this port and close it / make it use another port. Also please upload a log, it should contain more information about the issue.

**Comment by NicTanghe** [comment]
Weird because I was wrong and there are actually 2 errors.

The keyboard on the laptops emits the ASUS config and my external keyboard is using the aurora config. there is an issue there but i wil make a new bugreport for that one.

THDR > i was wrong.
