### ISSUE TITLE
Overwatch - Anyway to make keys brighter on some characters? 

### ISSUE THREAD

**Issue by Syloxane** [antonpup/Aurora#234]
Just wondering if there was anyway I could do this myself by editing the code  or something. Or if this might be done in a future update. Some characters in Overwatch like Widowmaker and Mccree for example have really dim lighting that can only be seen in the dark most of the time. Would be nice to make them light up more.

**Comment by antonpup** [comment]
I am assuming you have a Logitech keyboard. Overwatch profile has a "Color Enhancing" tab, which will let you control the threshold at which colors will be considered too dark and Aurora will brighten them up.

I will see about improving that system in the dev build.

**Comment by Syloxane** [comment]
Yea i have a Logitech G910 Spectrum , I have the Enhancing option all the way up but it doesn't really do anything to the characters that have really dim lighting. I'm happy to hear that you are looking at it though, thanks for the reply.

**Comment by antonpup** [comment]
There are actually two options that take part in color enhancing. Both can be modified in the file "%appdata%\Aurora\Profiles\overwatch\default.json" (or instead of default, the name of your created profile).

"colorEnhance_initial_factor" - The maximum factor of how much a color channel can contribute to the algorithm. Default: 3.0 (Note: it might be redundant, looking over at the code, it could be eliminated, that's probably why I don't have it as an option)
"colorEnhance_color_factor" - The threshold over which the color channel will be considered "too dark". Default: 90, Range: [0-255]

These two variables are used in the following algorithm: https://github.com/antonpup/Aurora/blob/master/Project-Aurora/Profiles/Overwatch/GameEvent_Overwatch.cs#L79

You mentioned that you could also change code if need be, the linked method handles colors enhancing for Overwatch, so go nuts.

**Comment by antonpup** [comment]
Have you played around with brightness options? I am fairly close to finishing old profile migration to new layers system. So I can include your changes that you found to be optimal for brightness.

**Comment by antonpup** [comment]
Next update will include a better way to brighten Overwatch profile. Look at #301
