### ISSUE TITLE
Aurora isn't detecting my Blackwidow keyboard

### ISSUE THREAD

**Issue by Nedo93** [antonpup/Aurora#239]
![reg](https://cloud.githubusercontent.com/assets/24442367/20986212/fb0e4ca6-bcc7-11e6-8273-b333b49472f2.jpg)

It seems like the software can't recognize my blackwidow chroma keyboard, I tried downloading the last version of both the Razer Synapse and Aurora and, but it seems like nothing changed.

Thank you in advance if you would provide me an answer.

**Comment by antonpup** [comment]
Yes, detecting Razer keyboard is a bit difficult, so it does not have automatic detection. (On that note, next major version doesn't detect keyboards at all because of this, so users have to manually select their keyboard).

But with that said, go to settings -> "Devices & Wrappers", and select Razer as your keyboard brand.
![](https://puu.sh/sHE1w/8e828864b3.png)

**Comment by Nedo93** [comment]
Thank you man, now it's working perfectly.
Thank you for the answer and the awesome software.

**Comment by antonpup** [comment]
No problem. Enjoy!
