### ISSUE TITLE
G810 Key Fade Effect Keypad Issue

### ISSUE THREAD

**Issue by BeefChamp** [antonpup/Aurora#268]
With the Key fade effect, when the "ENTER" key is pressed on the keypad, the other "ENTER" key lights up instead of the one I actually pressed.
And the same happens with numbers on the keypad. For example, the 7 key will light the "HOME" key and the 1 key will light up the "END" key, "." lights up "END", 4, 8, 6, and 2 light up the arrow keys, and 5 does nothing. Basically the whole  keypad is messed up

Also, having the media keys as editable keys would be great too.

**Comment by antonpup** [comment]
Windows doesn't differentiate between Numpad_Enter and Enter, likewise for Numpad_# and #.

The media keys aren't a part of the Logitech LED SDK. When they are, I will look into adding them.

**Comment by brainbug89** [comment]
Apps like games (e.g. CS:S) can differentiate between numpad keys and "normal" keys. Do the use another way to detect activated keys?

**Comment by antonpup** [comment]
I just looked over my implementation, it does allow for Numpad # keys. And they work fine. @BeefChamp had num lock off, which when pressed, Windows saw: Home, Up arrow, Page Up, etc... instead of numbers. That I cannot detect, because there's no such thing as "Numpad Home" etc. But the number keys work. The same goes for Enter and Numpad enter, I cannot detect a difference between them.

**Comment by LukasACH** [comment]
It would be possible to distinguish every indiviual key with a windows [low level keyboard hook](https://msdn.microsoft.com/en-us/library/windows/desktop/ms644959(v=vs.85).aspx). It would even allow detecting media key presses. I'm currently in the process of trying a possible implementation in Aurora of it, but I need to test the performance impact it would have and how to reduce it.
