### ISSUE TITLE
GameStateListener could not start.

### ISSUE THREAD

**Issue by yppdr** [antonpup/Aurora#270]
I have just "installed" the program but this error occurs, how to solve it? 

![Image of Troll](http://i.piotpilot.eu/8z02le.png)

And the Logs file : [Logs](http://pastebin.com/RMH0FXLG)

**Comment by antonpup** [comment]
Try running Aurora as administrator? If that does not work, restart your computer.

The error states: "The network location can not be reached. For information about troubleshooting the network, see Windows Help" Which is odd. I'm guessing another process is running something else on that port, or you have two instances of Aurora open.

**Comment by yppdr** [comment]
After restarting the PC and running the program as an administrator, I still have the same error. I have no other program to launch apart from avast, TS3 and Corsair Utility Engine.

**Comment by antonpup** [comment]
I will add a bit more informative error message that should hopefully fix your issue.

**Comment by TheRebelWizard** [comment]
I have also been getting this issue, it happens when I try to open Aurora from the traskbar icon while the program is minimized in the tray. Opening it from the tray works fine though. Wrong shortcut or something on the taskbar?

**Comment by antonpup** [comment]
@TheRebelWizard In the current public version, I had disabled check if Aurora was already running. Which is what you are experiencing. It will allow you to run another instance of Aurora, but it will crash as soon as it tries to allocate resources that are already allocated by the first instance of Aurora.

It's fixed in the next version. It will close the second instance, notifying the user that Aurora is already running.

**Comment by TheRebelWizard** [comment]
Wow speedy reply! 

Good to hear, thanks for all your work, and a happy holiday to you! Aurora has made me very happy! 👍 :)

**Comment by santosch** [comment]
As a temporary fix, you can open up your taskmanager and kill the already running aurora process. After that, you can launch the program again. (Got that in a few rare cases)
