### ISSUE TITLE
Bitmap resolution and animation smoothness

### ISSUE THREAD

**Issue by VoronFX** [antonpup/Aurora#277]
Hi! 
When I've been writing my scripts , at first I decided to use drawing on bitmap as easier way to deal width gradient and moving objects. But I've ended manually controlling color of each button cause of smoothness. 
Resolution of bitmap causes animations and transitions to be noticeably stepped.
While manually setting color we have about 255 shades, using bitmap drawing we get only about 5 shades.
I wonder if increasing resolution will significantly hit performance?
Maybe provide user choice between performance hit and smoothness?
Right now it's better to avoid using drawing on bitmap if we want to get fist-class quality animation and transitions.

**Comment by antonpup** [comment]
The time it takes to render 1 frame (as in after all layers have been sent to the engine) is very small at 0-1 ms and about 900-1500 ticks.

When I increase the bitmap of keys by 2, the results are similar. 
When x2: 0-1 ms, 1000-4000 ticks.
When x4: 2-6 ms, 8000-11000 ticks.
When x8: 9-15 ms, 29000-36000 ticks. (Animations begin to stutter)
When x16: 95-400 ms, 240000-1000000 ticks. (Animations stutter all over, performance isn't optimal at all)

I didn't want to go higher than the defined bitmaps because an average person won't notice the difference. Perhaps instead of increasing the bitmap size, we could include some smoothing via overlaying the previous frame at half opacity? It would give the color changing animations a bit more steps at the cost of adding one more layer. Which is very insignificant.

**Comment by VoronFX** [comment]
Nice idea but as drawback it can make smooth things that shouldn't be smooth. 
Anyway it's more like thing to consider when writing animations than a real problem. Just a better approach.
I am sure most of the animations could be manually calculated, it just take's a little more mind work.
After I re implemented mine's it even resulted in smaller code.

**Comment by antonpup** [comment]
You could manually save the previous layer that you want smooth animation on, set it to half opacity, and render it next time.

It wouldn't hurt other layers, will only affect layers that you implement this on.

**Comment by VoronFX** [comment]
Oh, you were talking about manually adding smoothness by overlaying. Now I got it. 
But the thing that caused me to open this discussion is rain fall away animation, it's great but it's really stutters a lot, painfully to see. It's not my animation but ok, I will see if I can re implement it.

**Comment by VoronFX** [comment]
In commit above I've made what I could.
Also I am thinking about making some kind of SmoothGraphics class which can be used as regular Graphics but will instead draw by keys. This will allow easily remake any existing drawing animating to be smooth and lightweight. I will do this if there would be free time.

**Comment by VoronFX** [comment]
I've just discovered that there is already a lot of useful functions for effects. Sadly I've known all them before, cause I've spent way too much time on implementing many things manually. I could made what I wanted much easier TT_TT. But that is my fault.
Still there are a lot of  missing functions? it will be great to extend it someday in future.

**Comment by antonpup** [comment]
What I can do is, for each layer add an option to "smooth" the layer. This will tie into scripts, as they will have a script layer.

This will allow user to select whether or not they want this smooth effect, as well as developers don't have to implement it.
