### ISSUE TITLE
Aurora 0.6.0 rainbow effect

### ISSUE THREAD

**Issue by sym5** [antonpup/Aurora#325]
Hi, just trying the pre-release and I loving it, but I set my keyboard up like in the previous version of aurora but with layers instead, I had a rainbow effect scrolling across the keyboard, so I created a new layer , gradient layer set it to rainbow & the animation is very clunky for want of a better word the transition form color to color is not smooth like it was if you use color zones, this only happens with the rainbow effect, it's smooth if i have a single color gradient, if I go back to using color zones its fine but that overrides the layer effects

**Comment by antonpup** [comment]
I looked into the gradient layer vs color zones, and I noticed little difference. What are the settings you are setting on the layer, so I could recreate the issue here?

The two are running fairly smoothly. Top is Gradient Layer with seamless rainbow at 2x speed. Bottom is Color Zone rainbow (horizontal) at 2x speed.
![](https://puu.sh/tdYKZ/a003b06cf4.gif)

Are you perhaps referring to the fact that current pre-release's animation speed is faster at 1x than Color Zone at 1x. Because that was fixed on dev ( https://github.com/antonpup/Aurora/commit/81768818eff57034b1f5c181d856efde739487e5 ) just waiting until I can push a proper update.

**Comment by sym5** [comment]
I didn't change any settings, just selected the rainbow seamless setting and left it at that, looking at your keyboard bitmap, it is not the same on mine. here's mine(sorry for the phone vid)
[](https://goo.gl/photos/oimgyshh9tk4rRf38url)

**Comment by antonpup** [comment]
Yours is choppy like that because you selected a sequence of keys. I selected a freestyle region. The result is the same either way, the choppiness doesn't affect the final result on the keyboard. As the keyboard eventually has to sample out a single color to choose from (which is equivalent to what you see on your bitmap).
