### ISSUE TITLE
[Rocket League] Goal Scoring

### ISSUE THREAD

**Issue by stuntguy3000** [antonpup/Aurora#357]
A new project (https://github.com/garrettjones331/Goalie/blob/master/DiscordBot/RocketLeague.cs) appears to have memory addresses for goal counting. Would love to see it in Aurora.

**Comment by antonpup** [comment]
Yeah... well... Here's the thing. It uses memory reading. If you look at every other issue opened here about Rocket League, I eventually say that I don't want to do memory reading because it's tedious having to update pointers for each RL update. It can be added, sure, but it means more time updating pointers after a new update.

**Comment by stuntguy3000** [comment]
Ah, fair enough

I've bugged Psyonix about adding GSI and they basically said not right now (read: never). Shame really.

**Comment by antonpup** [comment]
I've added the guy on steam. I'll see if something can be developed to work for both projects.
