### ISSUE TITLE
Version 0.6.0b no longer supports Corsair MM800 mousemat and Corsair Void headset

### ISSUE THREAD

**Issue by jmautari** [antonpup/Aurora#386]
Just upgraded from v0.5.0 and noticed Aurora no longer supports my Corsair MM800 RGB mousepad and Corsair Void RGB headset. Is there a workaround to get those devices detected again?

Thanks.

**Comment by antonpup** [comment]
The support is still there... I didn't remove it. Perhaps it's an issue with CUE?

**Comment by jmautari** [comment]
Version 0.6.0 has dropdowns to select devices but there are no dropdowns for mousepad and headset. I assume they should be detected automatically, but they aren't detected even clicking on Retry for connected devices.

Reverted to v0.5.0d and everything's working again. I will try v0.6.0b again and will post logs later.

Thanks.

**Comment by antonpup** [comment]
I just compared 0.5.1d and 0.6.0b and didn't find anything that would "break" support. The only major difference between the two is that I added ability to block lighting per device type. So please ensure that you have not checked "Disable X Lighting" in settings.
![](https://puu.sh/toUD4/1c9243f199.png)

Furthermore, I have Corsair keyboard, mouse, mousemat, and headset working perfectly fine with CUE 2 demos using version 0.6.0b.
[https://puu.sh/toUYY/675bfff272.mp4](https://puu.sh/toUYY/675bfff272.mp4)

I am sorry, this is going to sound rude. But it's a problem on your end, and I have no idea how to fix it. Because my test cases are working over here. So.... reinstall CUE or something. I have no idea.

**Comment by jmautari** [comment]
It haven't sounded rude at all. I give it a new try and it worked this time after recreating the zones so you were right, it was a problem on my end.

Sorry for bothering you with that and thanks for your support!

**Comment by jmautari** [comment]
Actually there's a detection problem going on, my mouse and headset weren't detected when I turned my computer on this morning, but everything was detected after restarting Aurora. But no problem, I can live with that. :)

Log attached
[2017_17_01.zip](https://github.com/antonpup/Aurora/files/711027/2017_17_01.zip)
