### ISSUE TITLE
[Request] Reactive lighting to be on parts of the keyboard I am not covering with my hand.

### ISSUE THREAD

**Issue by cjbeames** [antonpup/Aurora#434]
The lighting for games (Overwatch) right now is very cool. But it isn't really all that useful while in game. When your ultimate ability is ready though the whole keyboard flashes and it's hard to miss. There is a portion of the keyboard that is not being used (read: not obscured by my hand) for the majority of the time while gaming and it would be good in my view to use that portion to give feedback about what is going on with your character.
Numbers 5-0 could show health. Letter keys below that could show ability status. The current way is great if you're teaching someone how to play a game, you can say the keys that are lit are the ones you need to worry about. But if you're a bit more savvy then that they are not of much use at all.

**Comment by antonpup** [comment]
Overwatch lighting is Blizzard's own. Aurora simply redirects lighting to proper devices. GTA 5 lighting however, has customization with Aurora for some things.

I don't want to add further lighting customization for Overwatch because:
1. Their lighting implementation is okay
2. They actually provide dynamic lighting for key binds, so if you were to rebind H to B, B would then blink for "hero change". This makes it a bit difficult to "narrow down" specific game states. Because they can be broken by user simply reminding keys.

Same thing goes for the Division. When you load into the game, keyboard just lights up with all kinds of keybinds.

**Comment by cjbeames** [comment]
Is there no way to make a new profile that uses the same method for grabbing the game data but allows for some added extras?

**Comment by antonpup** [comment]
Like I said before, it can be done. But then instead of showing "original razer implementation" it would be converted into Aurora implementation, where the user would never see the original razer effects. This will also cause issues with updates, with newly added heroes, the background (and hero list) would have to be updated.

If you do want to show both original and Aurora implementation then, for example, the ultimate ability will be shown twice, once on Q in original, and another time where it's set to display in Overwatch.

I don't think it's worth the trouble to take apart a very well done lighting implementation.

**Comment by cjbeames** [comment]
Maybe we have crossed wires, could you not leave the current "original razer implementation" as is and then allow for you or someone else to add extra lighting effects to that under a whole new name "extra Overwatch implementation"
And, I have no idea how any of this works, but is the game not sending out a message to say "x ability [status]" and if so could that message not just be acted upon differently for a new profile?

**Comment by brainbug89** [comment]
> And, I have no idea how any of this works, but is the game not sending out a message to say "x ability [status]" and if so could that message not just be acted upon differently for a new profile?

No it's not. The game directly sends lighting information to the keyboard API like "key E red" whereby "red" is a color hex value. Thats the reason @antonpup mentioned "2. They actually provide dynamic lighting for key binds, so if you were to rebind H to B, B would then blink"

So it's not possible without alot of trouble.
