### ISSUE TITLE
A wild question/suggestion appeared!

### ISSUE THREAD

**Issue by selmansavas** [antonpup/Aurora#438]
Loving Aurora so far, would love to do something like this in future. My question is, is there anyway to bound self made custom profiles to certain applications? Ex. I made an overwatch profile but have to switch to it everytime i wanna play it. Thanks for everything and love your interaction with your users, keep up the good work! <3

**Comment by antonpup** [comment]
Every profile has at least 1 exe filename associated with it. If you're having to tab out and tab back in to activate profiles, you should change your Application Detection Method in the settings. But if you've made a generic profile for Overwatch, I wouldn't recommend doing that, because it can conflict with the pre-existing Overwatch profile.

> would love to do something like this in future

Time to stomp competition? :P

**Comment by selmansavas** [comment]
> Time to stomp competition? 
Maybe in near future but not now ^^
For profiles, i meant about the ones you create with layers and stuff. Is it possible to attach them to a application and such?
