### ISSUE TITLE
Swiss Keyboard Layout

### ISSUE THREAD

**Issue by Deltarr** [antonpup/Aurora#463]
Hello,

Thank you for this app.

Is there a way to setup Aurora for a Swiss Keyboard ?
At the moment I use the German version but some keys are missing or not located at the same place

Swiss keyboard layout
![](https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/KB_Swiss.svg/900px-KB_Swiss.svg.png)

German keyboard layout
![](https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/KB_Germany.svg/900px-KB_Germany.svg.png)

Is there a way to create a new layout in Aurora ?

Thank you

**Comment by brainbug89** [comment]
You could try and edit the layout file yourself: _Aurora\kb_layouts\Plain Keyboard\layout.de.json_ but you need to find the scancodes.

btw next time pls add "Swiss layout" to the issue title. :wink:

**Comment by Deltarr** [comment]
Thank you, I will try that.

I've modified the post title. Sorry.

**Comment by LukasACH** [comment]
There are some Keys mapped wrong while coloring the physical Keyboard, In Aurora, all keypresses show up at the correct Location.

I found the following Errors:
![ch_layout](https://user-images.githubusercontent.com/16141905/28749244-3b02e126-74c1-11e7-8938-95e940e01bbd.PNG)

| Pressed Keys | Lit Keys |
|:------------:|:--------:|
| 1 | Nothing |
| 2 | 4 |
| 3 | 5 |
| 4 | 6 |
| 5 | 1 |
| 6 | 7 |
| 7 | Nothing |
| 8 | 9 |
| 9 | 2 |
| y | z |
| z | y |

Keys 3 and 8 don't change color while the swiss Keyboard layout is selected.

**Comment by simon-wh** [comment]
@LukasACH So what you're describing is that the keys show properly when pressed in Aurora but the actual keys lit on the keyboard are wrong and don't match what is displayed in Aurora?

**Comment by LukasACH** [comment]
Yes. For example, if I press key 2 on my keyboard, then key 2 is highlighted in Aurora, but the color is applied to key 4.

**Comment by simon-wh** [comment]
@LukasACH Thanks for letting me know about this, I realized that I was forgetting a whole step to the process of adding layouts. I'm going to rewrite how the layouts work so it is less frustrating to do, but I'm going to do it after v0.6.1 is released because I don't want to introduce more bugs before it.

**Comment by simon-wh** [comment]
@LukasACH I'm just after saying I was going to wait until after v0.6.1 to rewrite this. But I'm going to do a bit of it now. My plan is to have pretty much all the layouts to use the same layout of DeviceKeys, but with the correct display character. The layout would include a conversion table of the device keys which corrects incoming keys to the correct device key, this means that the keys can be displayed correctly in  Aurora and can be converted to the specific keyboard device keys (Corsair, Logitech, etc) without having to include a ton of if statements for particular layouts. So far I haven't found any issues with this possible approach but I may discover something in the future. If this works it should allow for profiles that have layers that have keys assigned that are changed in layouts to light the same key instead of what ever it was converted to for that layout.

**Comment by LukasACH** [comment]
As a sidenote for consistency reasons, the ISO abbreviation for Switzerland is `ch`.
