### ISSUE TITLE
After Windows 10 update on april 10th-12th Aurora now crashes on launch with no error messages

### ISSUE THREAD

**Issue by Dormirre** [antonpup/Aurora#528]
### What are you experiencing an issue with?

- [x ] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ x] Crash
- [ ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
Aurora should be launching just fine, but closes shortly after i try to launch it.

### Actual behavior:
I click the shortcut to launch it and it just closes a few moments after its launch.
### How often does this problem occur?

This problem occurs... (Every time)

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. Go to shortcut
2. Launch it
3. Closes itself

### What is the version of Aurora you are experiencing this issue with?

My version is... (N/A)

### Does the previous version of Aurora have this issue?
The previous version, (Did not

), did/did not have this issue.

### Please include any logs, screenshots, or files that are related to this issue:

For logs, you can use: http://pastebin.com/
For screenshots, you can use: http://imgur.com/
For files, you can use: http://www.tinyupload.com/ , https://www.dropbox.com/, or attach them to the issue.
Gif of issue: https://gyazo.com/db54b5ba1f7dd907771ecc342e793dd0
Logs: https://www.dropbox.com/s/sww7yc4l49w8zym/2017_12_04.log?dl=0

**Comment by Denzof** [comment]
Hello I didn't want to create a new issue as well, but I have the same problem, I updated to new version of Win 10 and it stopped working just like this post and the one below. I saw you mention a dev version working well but mine isn't working at all I have the 6b most recent one and made sure no anti virus or defender will block it.


[2017_12_04.zip](https://github.com/antonpup/Aurora/files/917631/2017_12_04.zip)

**Comment by Dormirre** [comment]
Yes, I tried an older beta version of Aurora but still it closes itself. So odd

**Comment by antonpup** [comment]
We were able to narrow down the issue to be caused by Riva Tuner. Riva Turner is part of MSI Afterburner, it's used as an overlay for monitoring cpu/gpu/ram stats.

But point being, if Riva Tuner is running, it attempts to hook into Aurora, thus crashing Aurora through DirectX 9. A solution is to either not run Riva Tuner, or add Aurora to Riva Tuner applications list and set detection level to NONE. Like so:
![](http://i.imgur.com/hNUogLP.png)

If you're running Aurora from an extracted zip archive, then add Aurora.exe from the extracted archive to the list. If you've installed via web installer, the default install path is "C:\Program Files\Aurora", so add Aurora.exe from that path.
