### ISSUE TITLE
[Request] Final Fantasy XIV: ARR

### ISSUE THREAD

**Issue by RiveaJ** [antonpup/Aurora#582]
Hey, I just found Aurora and thought it would be brilliant to work alongside FFXIV.

I understand that would be a huge task but I'd be willing to donate time to help out.

**Comment by Thoth2020** [comment]
Hey there. I don't work on Aurora, but I worked on Artemis, a similar program. FF14 is one of my favorite games of all time, and I would have loved to add support for it.

In order to properly add support for a game like this, the game has to make some information about its gamestate available in an API or something like that.

Producer Naoki Yoshida has said that this is never going to happen because he doesn't want parsers or heal meters or other things in the game. I'm wildly paraphrasing here, but that's the long and short of it.

Now, there are programs that support FF14 on RGB keyboards, but they're all plugins for a program called Advanced Combat Tracker, or ACT. That's a parser that I think works by sniffing memory.

It would probably be preferable for Aurora, Artemis, et al to work to light your RGB keyboard by themselves, without hooking into ACT. The only way to do that would be to write their own parsers.

Presented with that, I'd rather spend 24 hours straight trying to clear T9 with a fresh set of noobs each run.

If you think you can write your own parser, and present combat and other gamestate data to Aurora, it would actually be a simple matter, from that point, to write the RGB integration. I don't know how much overhead that would put into Aurora though, and since I don't write it, that's not my comment to make.

This would be a tough one, though.

**Comment by Thoth2020** [comment]
Oh, and I have asked the FF14 dev team if this would ever be something they would do. The response I got was "We will take this idea into consideration with the rest of the team." If you don't know what that means from a Japanese business perspective: "No."

If it were to happen, they would do the implementation themselves... have you seen the level of detail that goes into every aspect of this game? They don't do things by halves. But I definitely feel your pain.

**Comment by simon-wh** [comment]
Closing until support is viable

**Comment by Thoth2020** [comment]
FF14 just added support but it looks like Logitech only. Still, that's a step!

**Comment by brainbug89** [comment]
@Thoth2020 did you try the Logitech wrapper patch from Aurora with FF14?

**Comment by chewston** [comment]
Hi there, it looks like the in-game wrapper doesn't work for me.
