### ISSUE TITLE
Key Fade

### ISSUE THREAD

**Issue by Xtreme976** [antonpup/Aurora#62]
Is there any was to make the key fade similar to the one logitech provides? In its current iteration it requires you to select two colors when all i want is one. Any way this could be added? I assume its an easy implementation

**Comment by antonpup** [comment]
You can set the secondary color as transparent.

**Comment by Xtreme976** [comment]
How do i do that? Thanks for the quick response :D

**Comment by Xtreme976** [comment]
Nvm found it! Thank you! :)

**Comment by antonpup** [comment]
In the dropdown, at bottom switch modes. Then it will appear as a list of colors. Somewhere towards the bottom (might be bottom row) there will be a transparent selection.

You might have to set to transparent and then change the base color from white to whatever your primary color is. So for example if primary is purple. Secondary would have to be a transparent purple. This is for a smooth animation. Otherwise it may fade from Purple to White(ish) to transparent.
