### ISSUE TITLE
Hello there. how/where do i find the information to get the software to read game data . example i would like the health of a character in the lego games to be displayed on the keyboard.

### ISSUE THREAD

**Issue by hottheadliberty** [antonpup/Aurora#635]
### What are you experiencing an issue with?

- [ ] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
Explain here what should happen.

### Actual behavior:
Explain here what happened instead.

### How often does this problem occur?

This problem occurs... (Fill in here)

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. 
2. 
3. 

### What is the version of Aurora you are experiencing this issue with?

My version is... (Fill in here)

### Does the previous version of Aurora have this issue?
The previous version, (Fill in the version here), did/did not have this issue.

### Please include any logs, screenshots, or files that are related to this issue:

For logs, you can use: http://pastebin.com/
For screenshots, you can use: http://imgur.com/
For files, you can use: http://www.tinyupload.com/ , https://www.dropbox.com/ , or attach them to the issue.

**Comment by simon-wh** [comment]
There is no definitive way to get information from a game. Games like CS:GO and Dota 2 where they use Game State Integration which is a JSON payload full of current data from the game. Other games like GTA 5, Overwatch, etc use wrappers for Razer/Logitech so the lighting is given to Aurora instead of where it originally was going. If you want to get Aurora to read the information you would need to find a viable option for getting that information which could be memory reading, gsi or something else and then to implement that method into Aurora. Just using the Software on its own you cannot magically get it to get information from a game that support hasn't been implemented
