### ISSUE TITLE
Aurora is doing "fatally crush"

### ISSUE THREAD

**Issue by harryleong** [antonpup/Aurora#682]
So yesterday I've downloaded this v0.6.0 patch and extracted it into another drive in my computer, before uninstalling the old ones.

Right after i uninstall the extracted patch of v0.6.0

This problem occurs

http://i.imgur.com/ez7LVKv.png

Also sometimes I can manage it to run, but the effects in DotA 2 doesn't seems to be working properly, as in hero specific skill special RGB effect, e.g. Razor's Plasma Field doesn't make my keyboard to ripple effect.

Also there's one more issue is that I can't assign my micro keys in the Dota 2 item button. I'm using Micro 1 in my Blackwidow Chroma but assigned with Numpad 7, I wanted my Micro 1 to glow instead of Numpad 7.

**Comment by DogeAmazed** [comment]
The crash happens, because the patch got new settings etc..
You can use the patch or you need to remove your Config (%APPDATA%/Aurora -> Config.json and Profiles). But I would suggest to make an backup before.

Maybe someone can implement an backup function, if there is a new version installed, so it won't corrupt the old files and you can downpatch.

**Comment by harryleong** [comment]
Hey thanks for your help, I've removed the config and profiles folder entirely and re-opened Aurora and it works. No longer having crash issue. 

Is there anyway to solve the issue to assign Micro key button on the setting? Blackwidow keyboard preview showed there as G1~G5, but I can't seems to be assign them in the Inventory & Stash key section.

Thanks again Doge!
