### ISSUE TITLE
League of Legends profile is not working.

### ISSUE THREAD

**Issue by KanyQan** [antonpup/Aurora#728]
I have Logitech G410, installed Aurora day ago and i noticed that my League of Legends profile isn't working. 

I already did this:
![1](https://user-images.githubusercontent.com/30931142/29217107-0be0bfb8-7eb1-11e7-9389-9926d926fe85.PNG)
![2](https://user-images.githubusercontent.com/30931142/29217113-0dcb28c2-7eb1-11e7-8078-2afe8f1089d3.PNG)
![3](https://user-images.githubusercontent.com/30931142/29217114-0ef98c16-7eb1-11e7-9d4b-9ca6655c9d54.PNG)
![4](https://user-images.githubusercontent.com/30931142/29217118-1006c4fc-7eb1-11e7-86e1-aa0594a992b6.PNG)

**Comment by simon-wh** [comment]
From the first image, the lighting won't display until you're in-game, there won't be any preview because the lighting information is from the game. I see that there is LogitechLed.dll in the LoL folder. Can you try changing the name of that to LogitechLed.dll.bak to see if it resolves the issue?

**Comment by KanyQan** [comment]
Thanks for quick anwser ! 
Sorry, changing the name of LogitechLed.dll didnt help at all, but at the start of the game keyboard flash green few times ( blue Q W E R only ), after that there is still nothing, just black.
Is there a possiblity that where i was trying to patch LightFX i accidently broke something ? Maybe i should reinstall the game ? Or Aurora ?

**Comment by simon-wh** [comment]
@KanyQan Could you try disabling LightFX in the config, removing the LightFX.dll and patch the Logitech wrapper in Aurora settings?

**Comment by KanyQan** [comment]
Now, when im enable League profile in Aurora, keyboard is green ( with blue Q W E R ), but still black in game.

**Comment by simon-wh** [comment]
@KanyQan The blue QWER is probably the Color Zones for the League profile. I'm not sure where the green background is, do you have any layers added?

**Comment by KanyQan** [comment]
No, i didnt add any layers.

**Comment by simon-wh** [comment]
Could you take a screenshot of the profile in Aurora then? Could you post your latest log file as well?

**Comment by KanyQan** [comment]
![6](https://user-images.githubusercontent.com/30931142/29223845-49b2ffc4-7ec8-11e7-9278-2a1b165581aa.PNG)


[2017_11_08.txt](https://github.com/antonpup/Aurora/files/1218548/2017_11_08.txt)

**Comment by simon-wh** [comment]
Could you try the [latest development release](https://github.com/antonpup/Aurora/releases) and repatch the wrapper and post the log after you've tried again?

**Comment by KanyQan** [comment]
[2017_11_08.txt](https://github.com/antonpup/Aurora/files/1218617/2017_11_08.txt)

I tried latest development release, repatch the wrapper, keyboard was black everytime, after turning on LightFX in config, keyboard is green ( with blue Q W E R ) in game.

**Comment by th3an7** [comment]
Try beta v0.6.0-dev2... I had the same problem in CSGO on latest dev but that one is working just fine.

**Comment by simon-wh** [comment]
@KanyQan Could you using dev3?

**Comment by lilfox666** [comment]
i am currently using dev3 and league is still not working. ive tried everythng, rocket league also doesnt work other then that i have no problems.

**Comment by th3an7** [comment]
It's me again - I asked around Rocket League modders and one guy made a modification for his program and now creates .json file with correct memory pointers every time they are changed (entering server, restarting PC/game) - problem is, they are just direct memory addresses so pointers are not needed and they show "0"...

I've checked if those addresses are actually working and they are indeed the same as those you can manually find with ex. Cheat Engine when you do pointer scan...

And here is the main problem - aurora still does not work for that game - I've checked logs and it shows:
`[ERROR] 31.12.2017 21:02:27: ProfilesManager.Update() Exception, System.NullReferenceException: Odwołanie do obiektu nie zostało ustawione na wystąpienie obiektu.
   w Aurora.Profiles.RocketLeague.GameEvent_RocketLeague.UpdateLights(EffectFrame frame)
   w Aurora.Profiles.LightingStateManager.Update()
   w Aurora.Profiles.LightingStateManager.<InitUpdate>b__63_0(Object g)`

Is it because pointers are equal to 0?? Example of .json file created by his program:
`{"Team": {"baseAddress": "1119903888","pointers": [ "0", "0", "0", "0", "0" ]},"Orange_score": {"baseAddress": "1119903884","pointers": [ "0", "0", "0", "0", "0" ]},"Blue_score": {"baseAddress": "1119907468","pointers": [ "0", "0", "0", "0", "0" ]},"Boost_amount": {"baseAddress": "679834944","pointers": [ "0", "0", "0", "0" ]}}`

**Comment by simon-wh** [comment]
I'll have a look into League as I have it downloaded. @th3an7 Could you provide me with what you're working with so I could fix up Aurora to work with it? Without looking at the code I assume it's because the json has strings instead of numbers for the pointers. If I can work with it directly it'd make it easier for me to get it working straight off.

**Comment by th3an7** [comment]
Sure - [here it is](https://drive.google.com/file/d/142v6am7ABfNR67curaJqQAYNUkdH5A08/view?usp=sharing)

One thing - you need to unpack everything to C:/ProjectAurora and manually create Pointers folder (names must be exact) - otherwise it won't work... then just open the game and AlphaConsole.exe - it should inject itself to the game and create .json file in Pointers folder you've created.

**Comment by simon-wh** [comment]
@th3an7 I tried it and set it up in the way you described and nothing was being created in the Pointers directory.

**Comment by th3an7** [comment]
@simon-wh you tried with admin rights? Maybe try clicking "confirm and apply" (the green button above)? Also it should say "injected..." or something like that on top of that program.

I can try it myself tomorrow as it's 4 am here...

PS: sometimes Windows defender says it's a virus and blocks it - try disabling AVs before running that...

**Comment by simon-wh** [comment]
@th3an7 I clicked "Save & Apply" and it said it had successfully hooked.

**Comment by th3an7** [comment]
@simon-wh Then if you've created Pointers folder inside ProjectAurora, it should create .json file...

Have you entered the game? I mean ex. private match with bots?

**Comment by simon-wh** [comment]
@th3an7 It's shown up now, wasn't straight away, but it's something to work with at least.

**Comment by simon-wh** [comment]
@th3an7 I tried it out at the time and forgot to give feedback, I got the pointers working, however, they don't properly work, at one point the orange score worked for a bit, but then stopped having the correct value and the others didn't work at all. I had to make a slight change for it to accept the pointers (which also requires the "0" entries to be removed all the "pointers" arrays).
