### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by geomag42** [antonpup/Aurora#758]
### What are you experiencing an issue with?

- [X] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [X] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
Program taking as much ram as needed.

### Actual behavior:
Program using 1.1-1.9 GB of RAM
### How often does this problem occur?

This problem occurs... Some Times

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. Run it in autostart, i guess?
2. 
3. 

### What is the version of Aurora you are experiencing this issue with?

My version is... 0.6.1 dev 3

### Please include any logs, screenshots, or files that are related to this issue:

For logs, you can use: http://pastebin.com/
For screenshots, you can use: http://imgur.com/
For files, you can use: http://www.tinyupload.com/ , https://www.dropbox.com/ , or attach them to the issue.

**Comment by simon-wh** [comment]
Could you look at the possible fix mentioned in #387?

**Comment by Bionicle06** [comment]
It happens to me, too. It looks like it only happens when its in autostart. It consumes 1-2GB RAM, the logs dont log anything enteresting, as far as i can say.

Here is the log from the whole day:
https://pastebin.com/pfeBhaDC

The fix didn't help me. It happens only in dev3 in dev2 it works normal.

**Comment by simon-wh** [comment]
@Bionicle06 What game are you playing when it starts going up in RAM usage?

**Comment by Bionicle06** [comment]
It's CS:GO but all profiles for the games are disabled.

**Comment by simon-wh** [comment]
I wasn't able to replicate the issue using my current dev version of Aurora. You can try [this build](https://www.dropbox.com/s/6lavqkpwqps4x9e/v0.6.1-dev3%20tr%20test.zip?dl=0) but I don't think it'll make a difference

**Comment by Bionicle06** [comment]
I tried it again with your build but nothing really changed, its now on 1 GB after playing CS:GO.
https://pastebin.com/9DSJGBqf

**Comment by CJ2311** [comment]
I'm getting similar issues on 0.6.1-dev3
I've upload my logs [here](https://u.biyori.moe/aNjLBsuA.log), since they slightly exceeded  the limit on pastebin.
Aurora works automatically starts using 150MB and that increases at an alarming rate (already at 500MB after 30 seconds of execution) until it fills up the RAM and windows automatically closes it or stops responding. This happens both if the program is started on boot or manually.

I was not getting any problems with dev2, and when trying the fix in #387, I simply get "Error: Unable to rebuild performance counter setting from system backup store, error code is 5" in the command prompt.
It's also worth noting that I updated from dev2, but did delete the appdata folder when doing so, which didn't seem to help.
However, using the test build linked here, and once again after deleting the entire AppData folder, the problem seems to have gone away. (Which was no the case when I just installed the test build here without deleting the AppData folder)

**Comment by simon-wh** [comment]
@CJ2311 What's the log you have after you using the build linked?

**Comment by CJ2311** [comment]
[Here](https://pastebin.com/W2wT530N) it is after having Aurora run for an hour.
RAM usage remained normal during that time.

**Comment by simon-wh** [comment]
@Bionicle06 Do you use the Equalizer layer? If so could you compare a run with and without using that Layer?

**Comment by simon-wh** [comment]
@CJ2311 Thanks, I think the memory leak you were experiencing was due to an issue in NAudio which is used in the Equalizer Layer.

**Comment by CJ2311** [comment]
I see, well for the record, I never used that layer since I installed any of the dev versions. Dunno if that information helps.
Also when I first used the test build without deleting the AppData, the steelseries error you can see a few times only on my last log was repeating similarly to NAudio (and therefore the memory leak was still present), but I deleted that log file, I'm afraid.

**Comment by simon-wh** [comment]
@CJ2311 You should disable any device integrations you have no devices for under the device manager to avoid unnecessary attempts at initializing them

**Comment by CJ2311** [comment]
I did that now, thanks for the advice :)

**Comment by diareuse** [comment]
Hey! I have disabled everything and Windows still gives me OOM cause Aurora takes almost 32GB of RAM. Tried #387 but had no luck whatsoever. Can't tell if logs will help ya cause I personally don't see anything wrong with it https://pastebin.com/287Yu94T. It just happens to OOM on random basis.

**Comment by simon-wh** [comment]
Can people experiencing this have a look at #874 ?

**Comment by simon-wh** [comment]
Any feedback?

**Comment by diareuse** [comment]
Well I haven't certainly experienced any OOMs since I updated to most recent version ;)
