### ISSUE TITLE
Inverted lights

### ISSUE THREAD

**Issue by Ulym38** [antonpup/Aurora#769]
This is a pretty simple issue :
- I'm using a Logitech G410 Keyboard with a AZERTY layout
- I'm using Aurora 0.6.1-dev3
- In the "Affected Keys" area, the keys are ZQSD but the keyboard lights up WASD.
Here is a screenshot : [http://imgur.com/a/10jos](http://imgur.com/a/10jos)

**Comment by simon-wh** [comment]
This occurs due to the changes I made which makes the internal aurora mapping based on the physical keys so that if someone with qwerty layout has a profile that lights wasd and shares it with someone using azerty then it would light the same physical keys, in that case being zqsd. The reason you see it listed as zqsd but wasd is lit is because currently what is displayed in the affected keys is the name of the physical key in qwerty and is not yet setup to display it as the key on the selected layout. From dev2(I think) onwards you'll need to rechoose the affected keys to light the correct areas for you. I'll use this issue for making sure the affected keys lists the key from the layout rather than the us key at that position.

**Comment by simon-wh** [comment]
Issue has been fixed in the way I described in my previous comment, fix will be available in the next release.
