### ISSUE TITLE
Profile Compatibility

### ISSUE THREAD

**Issue by NM1r** [antonpup/Aurora#789]
### What are you experiencing an issue with?
- [ ] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [x] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?
- [ ] Crash
- [ ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [x] Other, (Fill in another type of issue here)

If I create a desktop profile I am not able to load it into an application profile since it doesn't show up in the profile list even if I move it into the applications profile folder. Why are the profiles stored seperately and not compatible? Can I exchange profiles between different applications? How can I share profiles for specific applications?

### What is the version of Aurora you are experiencing this issue with?
My version is 0.6.0b

**Comment by simon-wh** [comment]
Each folder in the Profiles directory is for each application and stores the profiles relevant to them. In v0.6.0b I think the profiles won't be compatible with other applications due to the profile system in that version (in the dev builds they should carry over). If you have a profile that isn't working you should check the logs for errors. If you want to share a profile you copy the PROFILENAME.json and make sure it is dropped in the right place.
